# Generated by Django 5.2.7 on 2025-10-30 11:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_name', models.CharField(max_length=100, unique=True, verbose_name='Allowance Name')),
                ('allowance_type', models.CharField(choices=[('Percentage', 'Percentage of Basic'), ('Fixed', 'Fixed Amount')], default='Percentage', max_length=10, verbose_name='Allowance Type')),
                ('percentage_of_basic', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentage of Basic/Fixed Value')),
                ('limit_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Limit Per Month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allowance',
                'verbose_name_plural': 'Allowances',
                'ordering': ['allowance_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_present', models.BooleanField(default=False)),
                ('total_work_duration', models.DurationField(blank=True, null=True)),
                ('overtime_duration', models.DurationField(blank=True, null=True)),
                ('late_duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_name', models.CharField(max_length=100, unique=True, verbose_name='Deduction Name')),
                ('deduction_type', models.CharField(choices=[('Percentage', 'Percentage of Basic'), ('Fixed', 'Fixed Amount')], default='Percentage', max_length=10, verbose_name='Deduction Type')),
                ('percentage_of_basic', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentage/Fixed Value')),
                ('limit_per_month', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Limit Per Month')),
                ('is_tax_exempt', models.BooleanField(default=False, verbose_name='Is Tax Exempt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'ordering': ['deduction_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EarnLeaveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_month', models.PositiveIntegerField(default=1)),
                ('day_of_earn_leave', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Christmas, Diwali', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyPayGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_grade_name', models.CharField(max_length=100, unique=True, verbose_name='Pay Grade Name')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Hourly Rate')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hourly Pay Grade',
                'ordering': ['pay_grade_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_days', models.FloatField()),
                ('purpose', models.TextField()),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('reject_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement', models.FloatField(default=0.0, help_text='Total days allocated for this leave type in the current cycle.')),
                ('available_balance', models.FloatField(default=0.0, help_text='Current balance available to the employee.')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number_of_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100, unique=True, verbose_name='Grade Name')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('percentage_of_basic_g', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayGradeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Grade Specific Value')),
            ],
        ),
        migrations.CreateModel(
            name='PayGradeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Grade Specific Value')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField()),
                ('current_department_name', models.CharField(max_length=100)),
                ('current_designation_name', models.CharField(max_length=100)),
                ('current_salary', models.CharField(max_length=50)),
                ('current_pay_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('promoted_pay_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('promoted_salary', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(max_length=100)),
                ('termination_date', models.DateField()),
                ('notice_date', models.DateField()),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('warning_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100, unique=True, verbose_name='Work Shift Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('late_count_time', models.TimeField(blank=True, null=True, verbose_name='Late Count Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Shift',
                'verbose_name_plural': 'Work Shifts',
                'ordering': ['start_time'],
            },
        ),
    ]
