# Generated by Django 5.2.7 on 2025-10-30 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='company.department'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.leavetype'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.leavetype'),
        ),
        migrations.AddField(
            model_name='paygradeallowance',
            name='allowance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.allowance'),
        ),
        migrations.AddField(
            model_name='paygradeallowance',
            name='pay_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.monthlypaygrade'),
        ),
        migrations.AddField(
            model_name='monthlypaygrade',
            name='allowances',
            field=models.ManyToManyField(related_name='pay_grades', through='company.PayGradeAllowance', to='company.allowance'),
        ),
        migrations.AddField(
            model_name='paygradededuction',
            name='deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.deduction'),
        ),
        migrations.AddField(
            model_name='paygradededuction',
            name='pay_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.monthlypaygrade'),
        ),
        migrations.AddField(
            model_name='monthlypaygrade',
            name='deductions',
            field=models.ManyToManyField(related_name='pay_grades', through='company.PayGradeDeduction', to='company.deduction'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promoted_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_employees', to='company.department'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promoted_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_employees', to='company.designation'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.holiday'),
        ),
        migrations.AddField(
            model_name='termination',
            name='terminate_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termination',
            name='terminate_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warning',
            name='warning_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warning',
            name='warning_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'attendance_date')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type')},
        ),
        migrations.AlterUniqueTogether(
            name='paygradeallowance',
            unique_together={('pay_grade', 'allowance')},
        ),
        migrations.AlterUniqueTogether(
            name='paygradededuction',
            unique_together={('pay_grade', 'deduction')},
        ),
    ]
